main: co.redeker.Market
name: market
version: 1.0.0
author: Jonathan Redeker
commands:
   market:
      description: Enter/exit the market
      usage: /<command> [enter | exit]
      permission: market.access
      aliases: [mk]
   marketspawn:
      description: Sets the spawn location of the market
      usage: /<command>
      permission: market.location
      aliases: [mkspawn]
   marketdelay:
      description: Sets the teleport delay to the market
      usage: /<command>
      permission: market.delay
      aliases: [mkdelay]
   
permissions:
   market.*:
      description: Allows usage of all Market commands
      default: op
      children:
         market.access: true
         market.location: true
         market.delay: true
   market.access:
      description: Allows you to access the market
      default: true
   market.location:
      description: Allows you to set the location of the market
      default: op
   market.delay:
      description: Allows you to set the teleport delay when entering the market
      default: op